### PR TITLE
Some basic flash styling and numbers_to_currency additions

### PR DESCRIPTION
**Pull request by boveus**
Additions: I changed the messages to have some general css classes of "good_message" or "bad_message" for now and gave them some basic styling.  Also added two lines of code to add numbers_to_currency to places we call prices.

User Story: N/A

Concerns (code location):  
I couldn't find a good place for the flash message to pop onto the screen without either covering other text or covering buttons.  For now it should be unobtrusive enough.

Mentions to collaborators:
@djtrujillo @jayphodges @vaidashi 

Notes(if applicable):

### CODE REVIEW

**Comment by vaidashi** [comment]
Cool, should we merge this in during lunch before our check-in with Ilana or afterwards?

**Comment by djtrujillo** [comment]
Sounds good. We'll just cross the placement issue when it becomes one. looks good

**Review by jayphodges — COMMENTED** [review]
Changes look good, I do not forsee this merge causing any issues.

**Comment by jayphodges** [comment]
Looks good, merging in.

**Pull request merged**
