### PR TITLE
Styling

### PR DESCRIPTION
**Pull request by jayphodges**
Additions: 
Styling for cart, all items index, addition of incrementing cart icon, and update to cart in order to allow for subtotal (price * quantity).

User Story:
Styling

Concerns (code location):
Primarily styling so no major concerns, although this will require a manual merge.

Mentions to collaborators:
@boveus

Notes(if applicable):
Styling implemented with Materialize.

### CODE REVIEW

**Comment by vaidashi** [comment]
Let's merge the authentication piece first and then fix the conflicts from the styling piece.

**Comment by djtrujillo** [comment]
I think the style is great. We will have some testing issues and some merge conflicts to resolve before merging

**Comment by jayphodges** [comment]
Changes with merge look good, may have to adjust some small styling on the top navbar following this merge though.

**Comment by boveus** [comment]
The number_to_currency is awesome.  We should add that to all of our views that handle currency.  One note is that it won't work in rails c or our models, but it is, in fact, a real thing.

**Pull request merged**
