### PR TITLE
Stylelogin

### PR DESCRIPTION
**Pull request by boveus**
Additions:  Adjust font on the cart total.  Add a modal for the login page.  Add a way to handle if a guest is trying to check out to prompt them to login before checking out.

User Story: 9 

Concerns (code location):
We will need to eventually roll the floating login button login into a dropdown of some kind.

Mentions to collaborators:
@djtrujillo @jayphodges @vaidashi 

Notes(if applicable):

### CODE REVIEW

**Comment by jayphodges** [comment]
I like the popout, excellent implementation and does not look like there are any issues that will be caused by merging.

**Comment by vaidashi** [comment]
This should give us a good platform to start with as we proceed with user story 12

**Comment by djtrujillo** [comment]
I like this better than the login path page. For the checkout, they shouldn't have an option to checkout as a visitor

**Comment by boveus** [comment]
The tests were failing.  I had to fix some of the verbage for the login/logout buttons for our capybara tests.  They should be good now.

**Comment by boveus** [comment]
I'm submitting another PR for this.

**Pull request merged**
