### PR TITLE
Style button

### PR DESCRIPTION
**Pull request by boveus**
Additions:  Fix the layout issue for the admin dashboard.  I also refactored how the status dropdown button and controller work for filtering orders by status.  

User Story: N/A

Concerns (code location):

We may need to move the admin edit account button to the sidebar, but this will be a minor refactor.

Mentions to collaborators:
@djtrujillo @jayphodges @vaidashi 

Notes(if applicable):

### CODE REVIEW

**Comment by djtrujillo** [comment]
admin dashboard layout looks good

**Comment by vaidashi** [comment]
Nice, let's next add the item change status feature on admin item edit .

**Comment by boveus** [comment]
Changing the 'edit' button to be uncapitalized broke a few of the tests.  I just added a minor commit to fix that issue.

**Comment by jayphodges** [comment]
Looks great, surprising how difficult it was to decently implement the select button for admin orders though.

**Pull request merged**
